### ISSUE TITLE
The PHP >= 5.6 requirement has broken deployments.

### ISSUE THREAD

**Issue by oodgaard** [cocur/background-process#14]
Is there a feature in php 5.6 that is required to make this run? Can you update this to php >= 5.4 in composer.json unless you really need a feature only available in 5.6 ?

As a work around, will use version 0.5.

**Comment by florianeckerstorfer** [comment]
First, please always use a stable version. Never use `master` in production environments. Please, do not ever do this for any project. If people use the `master` in production open source maintainers need to take a lot more care to not break stuff and by breaking stuff we can improve the code we are writing.

Second, I set the minimum version to 5.6, because 5.4 is no longer maintained, there are no security fixes for this version of PHP available. Since BackgroundProcess deals with executing commands it helps me because I don't have to keep an eye out for security problems in 5.4. However, I could set it to 5.5 since that version is maintained until July 2016.

**Comment by florianeckerstorfer** [comment]
If you absolutely need to use PHP 5.4 fix the version of BackgroundProcess to **v0.5**.
